AllCops:
  TargetRubyVersion: 2.6

Style/WordArray:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/SymbolArray:
  Exclude:
    - 'spec/**/*'

Style/NumericPredicate:
  Enabled: false